[package]
name = "echo-prototypes"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.6.0"
bitcode = { version = "0.6.9", features = ["serde"] }
chacha20poly1305 = "0.11.0"
hkdf = { version = "0.13.0", features = ["kdf"] }
p256 = { version = "0.14.0", features = ["serde", "ecdh"] }
rand = "0.10.3"
rootcause = "0.13.0"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
thiserror = "2.0.21"
